### ISSUE TITLE
Add SignUp / Login  

### ISSUE THREAD

**Issue by Farhandroid** [arhanashik/PSTUian-android#1]

**Comment by arhanashik** [comment]
Requirement: 
1. User should be able to login/signup from Home Page(the page after Splash). 
2. Login/Sign up option should be shown in the top right corner of the Home Page(the exact design or location is open to improve). 
3. If user is logged in or signed up a circular user image(placeholder if no image) should be in the login/signup option's place. 
4. By clicking the image, user should be able to see own profile details. The details page can be same as StudentProfile activity(or different better design, if you can). But, the user should be able to change the data inside i.e. Profile Pic, name, password and every other info.
5. login fields: student id and password
6. signup fields: name, student id, password, student registration number, faculty and batch. Faculty and Batch should be dropdown option. The api for faculty and batches of that faculty is already available. When user selects a faculty, the batches should be loaded. (Suggestion: The faculty input can be taken from a confirmation popup before the user enters into the signup screen. The batch input can be taken in the same way if necessary.)

**Comment by arhanashik** [comment]
Done by Arhan Ashik
